/** Declaration file generated by dts-gen */

export = line_column;



declare namespace line_column {
    namespace prototype {
        function fromIndex(index: any): any;

        function toIndex(line: any, column: any): any;

        namespace fromIndex {
            const prototype: {
            };

        }

        namespace toIndex {
            const prototype: {
            };

        }

    }

}

