enum NodeNames {
  Program = 'Program',
  Else = 'Else',
  Condition = 'Condition',
  ConditionElse = 'ConditionElse',
  Include = 'Include',
  List = 'List',
  Text = 'Text',
  Assign = 'Assign',
  Global = 'Global',
  Local = 'Local',
  Macro = 'Macro',
  MacroCall = 'MacroCall',
  Interpolation = 'Interpolation',
  Attempt = 'Attempt',
  Recover = 'Recover',
  Comment = 'Comment',
  Switch = 'Switch',
  SwitchCase = 'SwitchCase',
  SwitchDefault = 'SwitchDefault',
  Break = 'Break',
  Function = 'Function',
  Return = 'Return',
  Compress = 'Compress',
  Import = 'Import',
  Stop = 'Stop',

  // Not supported
  // Escape = 'Escape',
  // NoEscape = 'NoEscape',
  // Visit = 'visit',
  // Recurse = 'Recurse',
  // Flush = 'Flush',
  // Lt = 'Lt',
  // Nested = 'Nested',
  // Nt = 'Nt',
  // Rt = 'Rt',
  // Setting = 'Setting',
  // T = 'T',
}

export default NodeNames
