enum NodeNames {
  Program = 'Program',
  Else = 'Else',
  Condition = 'Condition',
  ConditionElse = 'ConditionElse',
  Include = 'Include',
  List = 'List',
  Text = 'Text',
  Assign = 'Assign',
  Global = 'Global',
  Local = 'Local',
  Macro = 'Macro',
  MacroCall = 'MacroCall',
  Interpolation = 'Interpolation',
  Attempt = 'Attempt',
  Recover = 'Recover',
  Comment = 'Comment',
  Switch = 'Switch',
  SwitchCase = 'SwitchCase',
  SwitchDefault = 'SwitchDefault',
  Break = 'Break',
  Function = 'Function',
  Return = 'Return',
  Compress = 'Compress',
  Import = 'Import',
  Stop = 'Stop',
  Setting = 'Setting',
  Lt = 'Lt',
  Nt = 'Nt',
  Rt = 'Rt',
  T = 'T',
  Flush = 'Flush',

  // Not supported
  // Escape = 'Escape',
  // NoEscape = 'NoEscape',
  // Visit = 'visit',
  // Recurse = 'Recurse',
  // Nested = 'Nested',
}

export default NodeNames
