name: Node CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn --ignore-engines --frozen-lockfile
      - run: git diff --quiet --exit-code
      - name: Lint
        run: yarn lint
      - name: Check format
        run: yarn format-check
      - name: Test
        run: yarn test
        env:
          CI: true
      - name: Codecov
        uses: codecov/codecov-action@v1.0.15
        with:
          file: ./coverage/lcov.info
          flags: unittests
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install
        run: yarn --ignore-engines --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Release
        if: ${{ github.ref == 'master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
