name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn --ignore-engines --frozen-lockfile
      - run: git diff --quiet --exit-code
      - name: Lint
        run: yarn lint
      - name: Check format
        run: yarn format-check
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
        env:
          CI: true
      - name: Codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          flags: unittests
          yml: ./codecov.yml
